version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: rubocop-rspec
    versions:
    - "< 1.31, >= 1.30.a"
  - dependency-name: chartkick
    versions:
    - 4.0.0
    - 4.0.2
  - dependency-name: stripe
    versions:
    - 5.31.0
  - dependency-name: database_cleaner
    versions:
    - 2.0.0
