inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - script/rails
    - tmp/**/*

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
