development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 20
  database: github-actions-development
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 20
  database: github-actions
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
