#    Copyright 2017 Operation Paws for Homes
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# == Schema Information
#
# Table name: breeds
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime
#  updated_at :datetime
#

class Breed < ApplicationRecord
  has_many :primary_breed_dogs, class_name: 'Dog', foreign_key: 'primary_breed_id'
  has_many :secondary_breed_dogs, class_name: 'Dog', foreign_key: 'secondary_breed_id'

  SHELTERLUV_BREED = {
    "Affenpinscher"                     => "Affenpinscher",
    "Afghan Hound"                      => "Hound, Afghan",
    "Airedale Terrier"                  => "Terrier, Airedale",
    "Akbash"                            => "Akbash",
    "Akita"                             => "Akita",
    "Alaskan Malamute"                  => "Malamute, Alaskan",
    "American Bulldog"                  => "Bulldog, American",
    "American Eskimo Dog"               => "Eskimo, American",
    "American Hairless Terrier"         => "Terrier, American Hairless",
    "American Staffordshire Terrier"    => "Terrier, American Staffordshire",
    "American Water Spaniel"            => "Spaniel, American Water",
    "Anatolian Shepherd"                => "Shepherd, Anatolian",
    "Appenzell Mountain Dog"            => "Appenzell Mountain Dog",
    "Australian Cattle Dog (Blue Heeler)" => "Cattle Dog, Australian (Blue Heeler)",
    "Australian Kelpie"                 => "Kelpie, Australian",
    "Australian Shepherd"               => "Shepherd, Australian",
    "Australian Terrier"                => "Terrier, Australian",
    "Basenji"                           => "Basenji",
    "Basset Hound"                      => "Hound, Basset",
    "Beagle"                            => "Beagle",
    "Bearded Collie"                    => "Collie, Bearded",
    "Beauceron"                         => "Beauceron",
    "Bedlington Terrier"                => "Terrier, Bedlington",
    "Belgian Shepherd Dog Sheepdog"     => "Shepherd, Belgian Sheepdog",
    "Belgian Shepherd Laekenois"        => "Shepherd",
    "Belgian Shepherd Malinois"         => "Shepherd, Belgian Malinois",
    "Belgian Shepherd Tervuren"         => "Shepherd, Belgian Tervuren",
    "Bernese Mountain Dog"              => "Bernese Mountain Dog",
    "Bichon Frise"                      => "Bichon Frise",
    "Black and Tan Coonhound"           => "Hound, Black and Tan Coonhound",
    "Black Labrador Retriever"          => "Retriever, Black Labrador",
    "Black Mouth Cur"                   => "Black Mouth Cur",
    "Black Russian Terrier"             => "Terrier, Black Russian",
    "Bloodhound"                        => "Hound, Bloodhound",
    "Blue Lacy"                         => "Blue Lacy",
    "Bluetick Coonhound"                => "Coonhound, Bluetick",
    "Boerboel"                          => "Boerboel",
    "Bolognese"                         => "Bolognese",
    "Border Collie"                     => "Collie, Border",
    "Border Terrier"                    => "Terrier, Border",
    "Borzoi"                            => "Borzoi",
    "Boston Terrier"                    => "Terrier, Boston",
    "Bouvier des Flanders"              => "Flanders, Bouvier Des",
    "Boxer"                             => "Boxer",
    "Boykin Spaniel"                    => "Spaniel",
    "Briard"                            => "Briard",
    "Brittany Spaniel"                  => "Spaniel, Brittany",
    "Brussels Griffon"                  => "Griffon, Brussels",
    "Bull Terrier"                      => "Terrier, Bull",
    "Bullmastiff"                       => "Bullmastiff",
    "Cairn Terrier"                     => "Terrier, Cairn",
    "Canaan Dog"                        => "Canaan Dog",
    "Cane Corso Mastiff"                => "Mastiff, Cane Corso",
    "Carolina Dog"                      => "Carolina Dog",
    "Catahoula Leopard Dog"             => "Catahoula Leopard Dog",
    "Cattle Dog"                        => "Cattle Dog",
    "Caucasian Sheepdog (Caucasian Ovtcharka)" => "Sheepdog, Caucasian Ovtcharka",
    "Cavalier King Charles Spaniel"     => "Spaniel, Cavalier King Charles",
    "Chesapeake Bay Retriever"          => "Retriever, Chesapeake Bay",
    "Chihuahua"                         => "Chihuahua",
    "Chinese Crested Dog"               => "Chinese Crested Dog",
    "Chinese Foo Dog"                   => "Unknown",
    "Chinook"                           => "Unknown",
    "Chocolate Labrador Retriever"      => "Retriever, Chocolate Labrador",
    "Chow Chow"                         => "Chow Chow",
    "Cirneco dell'Etna"                 => "Unknown",
    "Clumber Spaniel"                   => "Spaniel, Clumber",
    "Cockapoo"                          => "Cockapoo",
    "Cocker Spaniel"                    => "Spaniel, Cocker",
    "Collie"                            => "Collie",
    "Coonhound"                         => "Coonhound",
    "Corgi"                             => "Corgi, Pembroke",
    "Coton de Tulear"                   => "Coton De Tulear",
    "Curly-Coated Retriever"            => "Retriever, Curly-Coated",
    "Dachshund"                         => "Dachshund",
    "Dalmatian"                         => "Dalmatian",
    "Dandi Dinmont Terrier"             => "Terrier, Dandi Dinmont",
    "Doberman Pinscher"                 => "Pinscher, Doberman",
    "Dogo Argentino"                    => "Dogo Argentino",
    "Dogue de Bordeaux"                 => "Dogue de Bordeaux",
    "Dutch Shepherd"                    => "Shepherd, Dutch",
    "English Bulldog"                   => "Bulldog, English",
    "English Cocker Spaniel"            => "Spaniel, English Cocker",
    "English Coonhound"                 => "Coonhound, English",
    "English Pointer"                   => "Pointer, English",
    "English Setter"                    => "Setter, English",
    "English Shepherd"                  => "Shepherd, English",
    "English Springer Spaniel"          => "Spaniel, English Springer",
    "English Toy Spaniel"               => "Spaniel, English Toy",
    "Entlebucher"                       => "Entlebucher",
    "Eskimo Dog"                        => "Eskimo Dog",
    "Feist"                             => "Feist",
    "Field Spaniel"                     => "Spaniel",
    "Fila Brasileiro"                   => "Brasileiro, Fila",
    "Finnish Lapphund"                  => "Lapphund, Finnish",
    "Finnish Spitz"                     => "Spitz, Finnish",
    "Flat-coated Retriever"             => "Retriever, Flat-Coated",
    "Fox Terrier"                       => "Terrier, Fox",
    "Foxhound"                          => "Foxhound, English",
    "French Bulldog"                    => "Bulldog, French",
    "Galgo Spanish Greyhound"           => "Greyhound",
    "German Pinscher"                   => "Pinscher, German",
    "German Shepherd Dog"               => "Shepherd, German",
    "German Shorthaired Pointer"        => "Pointer, German Shorthaired",
    "German Spitz"                      => "Spitz, German",
    "German Wirehaired Pointer"         => "Pointer, German Wirehaired",
    "Giant Schnauzer"                   => "Schnauzer, Giant",
    "Glen of Imaal Terrier"             => "Terrier, Glen of Imaal",
    "Golden Retriever"                  => "Retriever, Golden",
    "Gordon Setter"                     => "Setter, Gordon",
    "Great Dane"                        => "Great Dane",
    "Great Pyrenees"                    => "Pyrenees, Great",
    "Greater Swiss Mountain Dog"        => "Greater Swiss Mountain Dog",
    "Greyhound"                         => "Greyhound",
    "Harrier"                           => "Hound",
    "Havanese"                          => "Havanese",
    "Hound"                             => "Hound",
    "Hovawart"                          => "Unknown",
    "Husky"                             => "Husky",
    "Ibizan Hound"                      => "Hound, Ibizan",
    "Illyrian Sheepdog"                 => "Unknown",
    "Irish Setter"                      => "Setter, Irish",
    "Irish Terrier"                     => "Terrier, Irish",
    "Irish Water Spaniel"               => "Spaniel, Irish Water",
    "Irish Wolfhound"                   => "Hound, Irish Wolfhound",
    "Italian Greyhound"                 => "Greyhound, Italian",
    "Italian Spinone"                   => "Spinone, Italian",
    "Jack Russell Terrier"              => "Terrier, Jack Russell",
    "Jack Russell Terrier (Parson Russell Terrier)" => "Terrier, Parson Jack Russell",
    "Japanese Chin"                     => "Japanese Chin",
    "Jindo"                             => "Korean Jindo",
    "Kai Dog"                           => "Kai Dog",
    "Karelian Bear Dog"                 => "Karelian Bear Dog",
    "Keeshond"                          => "Keeshond",
    "Kerry Blue Terrier"                => "Terrier, Kerry Blue",
    "Kishu"                             => "Unknown",
    "Klee Kai"                          => "Klee Kai",
    "Komondor"                          => "Komondor",
    "Kuvasz"                            => "Kuvasz",
    "Kyi Leo"                           => "Unknown",
    "Labrador Retriever"                => "Retriever, Labrador",
    "Lakeland Terrier"                  => "Terrier, Lakeland",
    "Lancashire Heeler"                 => "Unknown",
    "Leonberger"                        => "Leonberger",
    "Lhasa Apso"                        => "Lhasa Apso",
    "Lowchen"                           => "Löwchen",
    "Maltese"                           => "Maltese",
    "Manchester Terrier"                => "Terrier, Manchester",
    "Maremma Sheepdog"                  => "Unknown",
    "Mastiff"                           => "Mastiff",
    "McNab"                             => "Sheepdog, Mcnab",
    "Miniature Pinscher"                => "Pinscher, Miniature",
    "Mountain Cur"                      => "Mountain Cur",
    "Mountain Dog"                      => "Mountain Dog",
    "Munsterlander"                     => "Unknown",
    "Neapolitan Mastiff"                => "Mastiff, Neapolitan",
    "New Guinea Singing Dog"            => "Unknown",
    "Newfoundland Dog"                  => "Newfoundland",
    "Norfolk Terrier"                   => "Terrier, Norfolk",
    "Norwegian Buhund"                  => "Buhund, Norwegian",
    "Norwegian Elkhound"                => "Elkhound, Norwegian",
    "Norwegian Lundehund"               => "Lundehund, Norwegian",
    "Norwich Terrier"                   => "Terrier, Norwich",
    "Nova Scotia Duck-Tolling Retriever" => "Retriever, Nova Scotia Duck-Tolling",
    "Old English Sheepdog"              => "Sheepdog, Old English",
    "Otterhound"                        => "Otterhound",
    "Papillon"                          => "Papillon",
    "Patterdale Terrier (Fell Terrier)" => "Terrier, Patterdale (Fell)",
    "Pekingese"                         => "Pekingese",
    "Peruvian Inca Orchid"              => "Unknown",
    "Petit Basset Griffon Vendeen"      => "Griffon, Petit Basset Vendeen",
    "Pharaoh Hound"                     => "Hound, Pharaoh",
    "Pit Bull Terrier"                  => "Terrier, Pit Bull",
    "Plott Hound"                       => "Hound, Plott",
    "Podengo Portugueso"                => "Unknown",
    "Pointer"                           => "Pointer",
    "Polish Lowland Sheepdog"           => "Sheepdog, Polish Lowland",
    "Pomeranian"                        => "Pomeranian",
    "Poodle"                            => "Poodle",
    "Portuguese Water Dog"              => "Water Dog, Portuguese",
    "Presa Canario"                     => "Canario, Presa",
    "Pug"                               => "Pug",
    "Puli"                              => "Puli",
    "Pumi"                              => "Unknown",
    "Rat Terrier"                       => "Terrier, Rat",
    "Redbone Coonhound"                 => "Coonhound, Redbone",
    "Retriever"                         => "Retriever",
    "Rhodesian Ridgeback"               => "Ridgeback, Rhodesian",
    "Rottweiler"                        => "Rottweiler",
    "Saint Bernard St. Bernard"         => "Saint Bernard",
    "Saluki"                            => "Saluki",
    "Samoyed"                           => "Samoyed",
    "Sarplaninac"                       => "Unknown",
    "Schipperke"                        => "Schipperke",
    "Schnauzer"                         => "Schnauzer",
    "Scottish Deerhound"                => "Hound, Scottish Deerhound",
    "Scottish Terrier Scottie"          => "Terrier, Scottish Scottie",
    "Sealyham Terrier"                  => "Terrier, Sealyham",
    "Setter"                            => "Setter",
    "Shar Pei"                          => "Pei, Shar",
    "Sheep Dog"                         => "Sheep Dog",
    "Shepherd"                          => "Shepherd",
    "Shetland Sheepdog Sheltie"         => "Sheepdog, Shetland",
    "Shiba Inu"                         => "Shiba Inu",
    "Shih Tzu"                          => "Shih Tzu",
    "Siberian Husky"                    => "Husky, Siberian",
    "Silky Terrier"                     => "Terrier, Silky",
    "Skye Terrier"                      => "Terrier, Skye",
    "Sloughi"                           => "Sloughi",
    "Smooth Fox Terrier"                => "Terrier, Fox, Smooth",
    "South Russian Ovtcharka"           => "Unknown",
    "Spaniel"                           => "Spaniel",
    "Spitz"                             => "Spitz",
    "Staffordshire Bull Terrier"        => "Terrier, Staffordshire Bull",
    "Standard Poodle"                   => "Poodle, Standard",
    "Sussex Spaniel"                    => "Spaniel, Sussex",
    "Swedish Vallhund"                  => "Vallhund, Swedish",
    "Terrier"                           => "Terrier",
    "Thai Ridgeback"                    => "Ridgeback, Thai",
    "Tibetan Mastiff"                   => "Mastiff, Tibetan",
    "Tibetan Spaniel"                   => "Spaniel, Tibetan",
    "Tibetan Terrier"                   => "Terrier, Tibetan",
    "Tosa Inu"                          => "Unknown",
    "Toy Fox Terrier"                   => "Terrier, Toy Fox",
    "Treeing Walker Coonhound"          => "Coonhound, Treeing Walker",
    "Vizsla"                            => "Vizsla",
    "Weimaraner"                        => "Weimaraner",
    "Welsh Corgi"                       => "Corgi, Welsh",
    "Welsh Springer Spaniel"            => "Spaniel, Welsh Springer",
    "Welsh Terrier"                     => "Terrier, Welsh",
    "West Highland White Terrier Westie" => "Terrier, West Highland White Westie",
    "Wheaten Terrier"                   => "Terrier, Wheaten",
    "Whippet"                           => "Whippet",
    "White German Shepherd"             => "Shepherd, White German",
    "Wire Fox Terrier"                  => "Terrier, Wire Fox",
    "Wire-haired Pointing Griffon"      => "Griffon, Wire-Haired Pointing",
    "Wirehaired Terrier"                => "Terrier, Wirehaired",
    "Xoloitzcuintle (Mexican Hairless)" => "Xoloitzcuintle (Mexican Hairless)",
    "Yellow Labrador Retriever"         => "Retriever, Yellow Labrador",
    "Yorkshire Terrier Yorkie"          => "Terrier, Yorkshire, Yorkie",
    "Icelandic Sheepdog"                => "Unknown",
    "Hamiltonstovare"                   => "Unknown",
    "Miniature Schnauzer"               => "Schnauzer, Miniature",
    "Mixed Breed"                       => "Mixed Breed (Medium)",
    "Rough Collie"                      => "Collie, Rough",
    "Smooth Collie"                     => "Collie, Smooth",
    "Spanish Water Dog"                 => "Unknown",
    "Standard Schnauzer"                => "Schnauzer, Standard",
    "Wirehaired Dachshund"              => "Dachshund, Standard Wire Haired",
    "American Foxhound"                 => "Foxhound, American",
    "Miniature Bull Terrier"            => "Terrier, Bull",
    "Miniature Dachshund"               => "Dachshund, Miniature Smooth Haired",
    "English Foxhound"                  => "Foxhound, English",
    "Toy Manchester Terrier"            => "Terrier, Manchester",
    "Pembroke Welsh Corgi"              => "Corgi, Pembroke",
    "Miniature Poodle"                  => "Poodle, Miniature",
    "Pyrenean Shepherd"                 => "Unknown"
}.freeze

  def display_name
    name
  end

  def to_shelterluv_breed
    SHELTERLUV_BREED[name]
  end

end
